### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 442: character maps to <undefined>

### ISSUE THREAD

**Issue by Animatea** [mondeja/mkdocs-mdpo-plugin#56]
`(venv) PS C:\Users\den25\PycharmProjects\tense\mkdocs-theme> mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: C:\Users\den25\PycharmProjects\tense\mkdocs-theme\site
ERROR    -  Error building page 'C:\Users\den25\AppData\Local\Temp\mkdocs_mdpo_q39usco_\fr\index.md': 'charmap' codec can't encode character '\xe8' in position 442: character maps to
            <undefined>
Traceback (most recent call last):
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\den25\PycharmProjects\tense\venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\mkdocs\__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\mkdocs\commands\build.py", line 314, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\mkdocs\commands\build.py", line 220, in _build_page
    output = config['plugins'].run_event(
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\mkdocs\plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "C:\Users\den25\PycharmProjects\tense\venv\lib\site-packages\mkdocs_mdpo_plugin\plugin.py", line 736, in on_post_page
    f.write(output)
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 442: character maps to <undefined>`

&&

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte`

I completely copied these two examples:
https://github.com/mondeja/mkdocs-mdpo-plugin/tree/master/examples/material-theme
https://github.com/mondeja/mkdocs-mdpo-plugin/tree/master/examples/mkdocs-theme

But each gave the same error when `mkdocs build` / `mkdocs serve`
I don't understand what is causing the error

**Comment by mondeja** [comment]
Fixed in v0.0.27
